# Site settings
title: Wasin's Micro Blog
email: haxpor@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I blog about projects I'm working on. Mostly about mobile games, tech, web service, little tiny things I built for myself or for public, and tech/game industry-wide. Currently I'm living in Shenzhen, China. I'm running a small development company here.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://wasin.io" # the base hostname & protocol for your site
twitter_username: haxpor
github_username:  haxpor
instagram_username: haxpor

# Build settings
markdown: kramdown
