# Site settings
title: Wasin's Blog
title_part1: Wasin
title_part2: "'s Blog"
email: haxpor@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I blog about projects I'm working on. Mostly about mobile games, tech, web service, little tiny things I built for myself or for public, and tech/game industry-wide. Currently I'm living in Shenzhen, China. I'm running a small creative company with my girlfriend here.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.wasin.io" # the base hostname & protocol for your site
dashboardurl: "http://dashboard.wasin.io" # blog is another sub-domain, this is for its dashboard
twitter_username: haxpor
github_username:  haxpor
instagram_username: haxpor

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

#
# Jekyll-Assets configuration
#
assets:
  compress:
    css: sass
    js:  uglifier

  assets:
    - "*.png"
    - "*.jpg"
    - "*.jpeg"
    - "*.gif"
    - "*.html"

  sources:
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/htmls
    - _assets/css
